name: Deploy Infrastructure
on:
  workflow_run:
    workflows: ["Publish Bicep Registry"]
    branches: [main]
    types: 
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with: 
          deploymentName: DataLandingZone
          scope: subscription
          region: westeurope
          subscriptionId: ${{ secrets.AZ_SUBSCRIPTION }}
          template: ./main.bicep
          parameters: parameters.json
