name: Integration Tests 
on:
  push:
    workflow_run:
      workflows: ["Deploy Infrastructure"]
      branches: [main]
      types: 
        - completed

jobs:
  integration-tests:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: publish 
      uses: azure/powershell@v1
      with: 
      inlineScript: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.3.3 -Confirm:$false -Force
        Invoke-Pester -Path "tests"        
      azPSVersion: "latest"